version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    build:
      doxygen:
        - cd docs
        - doxygen Doxyfile
    post_build:
      - cp -r docs/build/html $READTHEDOCS_OUTPUT/html
