version: 2
formats: [html, pdf]

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    build:
      html:
        - doxygen docs/Doxyfile
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cp -r build/html $READTHEDOCS_OUTPUT/html
      pdf:
        - doxygen docs/Doxyfile
        - cd build/latex && make
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - cp -r build/latex/refman.pdf $READTHEDOCS_OUTPUT/pdf/index.pdf
