version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    build:
      doxygen:
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip/
        - cd docs
        - doxygen Doxyfile
        - mv build/html/index.html index.zip
        - cp -r build/html/* $READTHEDOCS_OUTPUT/htmlzip/
