name: General code checks
on: pull_request

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting using clang-format.
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "18"
