name: Compile for AVR Architecture
description: Compiles various parts of the code for AVR architecture using AVR GCC compiler
on: pull_request

jobs:
  compile:
    name: Compile library for AVR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: ./.github/actions/avr-toolchain
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          c-compiler: avr-gcc
