name: Test code
description: Tests driver without a hardware using unit and integration tests
on: pull_request

jobs:
  tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            BUILD_TESTING=ON
      - name: Run tests
        working-directory: ./build
        run: make test
