name: Test code
description: Tests driver without a hardware using unit and integration tests
on: pull_request

jobs:
  test-unit:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Run unit tests
        working-directory: ./tests
        run: make unit

  test-integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    if: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Run integration tests
        working-directory: ./tests
        run: make integration
